// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB6UNZJ3zajacfLLZv8CBN1A7n3q0w07M',
    appId: '1:498601929423:web:1eb3269d5a380e7eb565ba',
    messagingSenderId: '498601929423',
    projectId: 'mynotes-flutterproject-first',
    authDomain: 'mynotes-flutterproject-first.firebaseapp.com',
    storageBucket: 'mynotes-flutterproject-first.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV8xQHcUi7NNwdjuFKhg-cZSaOXGgRBvg',
    appId: '1:498601929423:android:805f07eef1a4a88eb565ba',
    messagingSenderId: '498601929423',
    projectId: 'mynotes-flutterproject-first',
    storageBucket: 'mynotes-flutterproject-first.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqO_Vh07IyAvjOIomDhmhYnTZbltuKSfc',
    appId: '1:498601929423:ios:d5f4940297e8678db565ba',
    messagingSenderId: '498601929423',
    projectId: 'mynotes-flutterproject-first',
    storageBucket: 'mynotes-flutterproject-first.appspot.com',
    iosClientId: '498601929423-gt31brl9m4r52c7qt0ki3l3jhvsa3dhe.apps.googleusercontent.com',
    iosBundleId: 'com.mike.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqO_Vh07IyAvjOIomDhmhYnTZbltuKSfc',
    appId: '1:498601929423:ios:d5f4940297e8678db565ba',
    messagingSenderId: '498601929423',
    projectId: 'mynotes-flutterproject-first',
    storageBucket: 'mynotes-flutterproject-first.appspot.com',
    iosClientId: '498601929423-gt31brl9m4r52c7qt0ki3l3jhvsa3dhe.apps.googleusercontent.com',
    iosBundleId: 'com.mike.mynotes',
  );
}
